### PR TITLE
Add external chat events

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Maxopoly** [comment]
You forgot to add the event to chat messages being sent because of commands (/gc, /r, /msg)

Aside from that this looks good

**Comment by ghost** [comment]
oh, right. doh

**Comment by ProgrammerDan** [comment]
Can you also add _back_ in the really nice https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/AsyncPlayerChatEvent.html#getFormat()

So that PEXPrefix isn't broken. I can't use this version as it is, until that integration is restored. It's only needed for global chat messages; PM and Group messages should not use the custom format.

https://github.com/DevotedMC/PEXPrefix

It's one of our donator rank rewards, so it's effectively top priority. No changes to this fork will go live until that integration is restored.

**Comment by ProgrammerDan** [comment]
Just for reference, here's how it used to use the getFormat(): https://github.com/DevotedMC/CivChat2/blob/3b3101165f64eb0879ad9f65ef12470ea08bc15a/src/vg/civcraft/mc/civchat2/CivChat2Manager.java#L308

Something along those lines should be preserved.

**Comment by ghost** [comment]
Ok I think I added what you need.

**Comment by ProgrammerDan** [comment]
Looks pretty good, @Maxopoly do the fixes satisfy your concerns as well?

**Comment by ghost** [comment]
just a note, this won't fire events when sending messages to other shards. I was assuming that was ok since sharding isn't going to be used anymore.

Biggest reason is there's no receiver Player instance for shard messages and I didn't want to make a new shard event for something that isn't used or will probably get removed.

**Comment by ProgrammerDan** [comment]
Yeah it'd be easy to add though, just hook into the chat event message within the Mercury Listener.

I guess we can leave it as an exercise for the mainline if nice things are wanted and someone keeps maintaining sharding.

**Comment by ghost** [comment]
then there's no sender instance. You could pass a null arg but that seems messy.

**Comment by ProgrammerDan** [comment]
Yeah, you'd probably have to spoof an OfflinePlayer or something like that.

**Comment by ghost** [comment]
bump

**Comment by ProgrammerDan** [comment]
```
[12:40:26 WARN]: [CivChat2] Task #5868 for CivChat2 v1.3.5 generated an exception
java.lang.NoClassDefFoundError: vg/civcraft/mc/mercury/MercuryAPI
        at vg.civcraft.mc.civchat2.CivChat2Manager.sendGroupMsg(CivChat2Manager.java:515) ~[?:?]
        at vg.civcraft.mc.civchat2.listeners.CivChat2Listener$1.run(CivChat2Listener.java:112) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

Please verify that things don't have hard dependencies on Mercury.

**Pull request merged**
