### PR TITLE
Stop using NameAPI to get player names

### PR DESCRIPTION
**Pull request by TealNerd**

### CODE REVIEW

**Comment by DevotedServant** [comment]
Can one of the admins verify this patch? @ProgrammerDan @Maxopoly

"ok to test" will build any commits made to this PR
"test this please" will build this PR once
"retest this please" will make another single build for this PR
"add to whitelist" will whitelist the creator of this PR and make jenkins automatically build any PRs made by him

**Comment by ProgrammerDan** [comment]
@Rourke750 I know you don't normally check this repo, but is there any reason you recall that CivChat used NameAPI in some spots (but not everywhere?)?

**Comment by rourke750** [comment]
Different authors did different things. Its better to use it as it will always guarantee the correct name you want to use.

**Comment by ProgrammerDan** [comment]
Given if Namelayer is running, the NMS changes the GameProfile's version of name (used in DisplayName and other places), is there any real advantage?

**Comment by rourke750** [comment]
So the issue there is that some places I believe cache the player name and end up loading it before namelayer has the chance to change the name. So in some of the chat components it doesn't change properly hence why namelayer has to still set the players displayname and other stuff using bukkit methods I believe some of the command stuff is weird as well. 
I haven't looked at anything Minecraft for a very long time so I'm not entirely sure how certain things are anymore. If you remove the NameAPI stuff and it works then great otherwise no real point in removing it as civchat needs the dependency anyways.

**Comment by ProgrammerDan** [comment]
Thanks for taking the time out to comment, rourke :)

**Comment by rourke750** [comment]
Np. Sometimes I want to get back into this stuff because I haven't coded anything lately. I just need to stop being lazy and work on other stuff I have going on lol.

**Comment by ProgrammerDan** [comment]
:D I'm sure the downtime has been healthy, don't begrudge it too much.

**Pull request closed without merging**
