### PR TITLE
Change behavior of /groupc

### PR DESCRIPTION
**Pull request by awoo-civ**
Fixes https://github.com/DevotedMC/CivChat2/issues/20

Tested.

### CODE REVIEW

**Comment by DevotedServant** [comment]
Can one of the admins verify this patch? @ProgrammerDan @Maxopoly

"ok to test" will build any commits made to this PR
"test this please" will build this PR once
"retest this please" will make another single build for this PR
"add to whitelist" will whitelist the creator of this PR and make jenkins automatically build any PRs made by him

**Comment by ProgrammerDan** [comment]
@TealNerd anyone else (sharpcastle?) any comments on this? Otherwise merging soon.

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by DevotedServant** [comment]
Build finished.

**Comment by Maxopoly** [comment]
Good change

**Pull request merged**
